version: "3"

services:
    postgres:
        container_name: fastFoodProdutosPostgresdb
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: fast_food
            POSTGRES_USER: fast_food
            POSTGRES_PASSWORD: fast_food
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
            interval: 10s
            timeout: 5s
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - fastFoodNetwork
    api:
        container_name: fastFoodProdutosApi
        build: "."
        working_dir: /fastFood
        environment:
            NODE_ENV: development
            POSTGRES_DB: fast_food
            POSTGRES_DB_HOST: postgres
            POSTGRES_DB_PORT: 5432
            POSTGRES_DB_USER: fast_food
            POSTGRES_DB_PASSWORD: fast_food
        command: sh -c "npm run generate && npm run migrate && npm run start"
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - "6001:6001"
        networks:
            - fastFoodNetwork
networks:
    fastFoodNetwork:
        driver: bridge

volumes:
    pgdata:
